version = 1

[update]
ignored_usernames = ["renovate"]
always = true

[merge]
blocking_labels = ['blocked']
method = 'squash'

[merge.message]
title = 'pull_request_title'
strip_html_comments = true
include_coauthors = true