version = 1

[merge]
require_automerge_label = true
blocking_labels = ['blocked']
method = 'squash'

[merge.message]
title = 'pull_request_title'
strip_html_comments = true
include_coauthors = true

[update]
ignored_usernames = ["renovate[bot]"]
always = true