version = 1

[update]
ignored_usernames = ["dependabot"]
always = true

[merge]
blocking_labels = ['blocked']
method = 'squash'
delete_branch_on_merge = true

[merge.message]
title = 'pull_request_title'
strip_html_comments = true
include_coauthors = true