version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3