version: "3.8"

services:
  sentry:
    image: "ghcr.io/penpow/sentry"
    labels:
      - com.centurylinklabs.watchtower.enable
    tty: true
    env_file:
      - .env

  watchtower:
    image: containrrr/watchtower
    restart: always
    ports:
      - 8909:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --label-enable --http-api-update --http-api-token updatesentry