version: "3.8"

services:
  bot:
    build:
      dockerfile: docker/Dockerfile
      context: ./
    tty: true
    env_file:
      - .env
    links:
      - db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    
volumes:
  db:
    driver: local