name: Issue report
description: Report an issue with Sentry
labels: [bug, need repro]
body:
  - type: textarea
    id: description
    attributes:
      label: Issue description
      description: Please provide us with the issue you are facing
    validations:
      required: true
  - type: textarea
    id: code_sample
    attributes:
      label: Code sample
      description: |
        Your code sample should be:
        1. Minimal - Use as little code as possible that still produces the same problem (and is understandable)
        2. Complete - Provide all parts someone else needs to reproduce your problem
        3. Reproducible - Test the code you're about to provide to make sure it reproduces the problem

        Follow the stack overflow advice to produce the code sample.

        This will be automatically formatted into code, so no need for backticks.
      render: typescript
  - type: textarea
    id: versions
    attributes:
      label: Versions
      description: Please list the version that this issue is being seen on
      placeholder: |
        vX.X.X
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Issue priority
      description: Please be realistic. If you need to elaborate on your reasoning, please use the issue description field above.
      options:
        - Low (slightly annoying)
        - Medium (should be fixed soon)
        - High (immediate attention needed)
    validations:
      required: true