name: Continuous Integration

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - .gitignore
      - .github/**
      - branding/*
  pull_request:
    branches:
    - main

jobs:
  Linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Add problem matcher
        run: echo "::add-matcher::.github/problemMatchers/eslint.json"

      - name: Use Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: yarn install --immutable --check-cache

      - name: Run ESLint
        run: yarn run lint

  Building:
    name: Compile source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Add problem matcher
        run: echo "::add-matcher::.github/problemMatchers/tsc.json"

      - name: Use Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: yarn install --immutable --check-cache

      - name: Build Code
        run: yarn run build